# Generated by Django 4.2.6 on 2023-10-06 12:13

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('url', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=8)),
                ('requested_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('url', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='url.url')),
            ],
        ),
    ]
